export const LOADING = 'LOADING'
export const REFRESHING = 'REFRESHING'

export const SAVE_USER = 'SAVE_USER'
export const SAVE_TOKEN = 'SAVE_TOKEN'
export const LOGOUT = 'LOGOUT'

export const GET_FAQS = 'GET_FAQS'

export const GET_ALL_STAFF = 'GET_ALL_STAFF'

export const GET_RISKS = 'GET_RISKS'

export const GET_INDIVIDUAL_CUSTOMERS = 'GET_INDIVIDUAL_CUSTOMERS'
export const GET_CORPERATE_CUSTOMERS = 'GET_CORPERATE_CUSTOMERS'
